### ISSUE TITLE
[Feature Request] Support MongoDB if using Prisma

### ISSUE THREAD

**Issue by gramliu** [nicoalbanese/kirimase#106]
During `kirimase init`, the only supported options right now are PostgreSQL, MySQL, and SQLite, likely because those are the only supported options by Drizzle. However, if we choose Prisma as our ORM, I think it would be incredibly valuable to have MongoDB as an option, even if initially we can only leverage just the SQL-esque features.

**Comment by nicoalbanese** [comment]
Hey 👋  thanks for the suggestion! I'm afraid MongoDB support isn't going to to be something I'll be looking to support. But should you want to still use Kirimase for the quick initialising of packages, it looks like configuring mongo is a simple one line addition to your prisma schema file:

```
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}
```
source: https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/mongodb/connect-your-database-typescript-mongodb
