### ISSUE TITLE
GoogleProvider returns the same user after choosing a different account

### ISSUE THREAD

**Issue by josephdburdick** [nicoalbanese/kirimase#111]
I have tested out the GoogleProvider by logging into my primary email, a gmail address, and that worked fine. 
When I try my alternative @gmail address this setup ignores it and logs in as the first address. 

I have not changed anything about this setup.

Steps to reproduce:
1. I log in and the session correctly reports my name and email
2. I sign out
3. I log back in but choose a different gmail address
4. The session remains the first email, name, etc

**Comment by nicoalbanese** [comment]
Very strange - I've just tried to recreate but am unable to. Assume you are using next auth here?

**Comment by josephdburdick** [comment]
Yes, I am using next-auth. I will try again from scratch.

**Comment by josephdburdick** [comment]
I have started from scratch. I have found my issue: I wanted to migrate my previous Supabase instance into this one and the migrations had typos– specifically because the models were singular instead of plural. I will close this issue now.

**Comment by josephdburdick** [comment]
I will say the issue with the typos is that there were differences between user/users, account/accounts, verificationToken/verification_token. It might be wise to consider allowing these table names be defined in a config or something before hardcoding them.
