### ISSUE TITLE
Missing DB Generate command

### ISSUE THREAD

**Issue by thecmdrunner** [nicoalbanese/kirimase#120]
**Config File**
```json
{
  "hasSrc": true,
  "packages": [
    "drizzle",
    "trpc",
    "next-auth",
    "shadcn-ui",
    "stripe"
  ],
  "preferredPackageManager": "pnpm",
  "t3": true,
  "alias": "@",
  "rootPath": "src/",
  "orm": "drizzle",
  "auth": "next-auth",
  "provider": "planetscale",
  "driver": "mysql",
  "componentLib": "shadcn-ui"
}
```

**Describe the bug**
There's a `db:generate` command shown after `kirimase init` but no generate script is found in the `package.json`.

**To Reproduce**
1. Run `kirimase init` after T3 setup - drizzle, next-auth, tailwind.
2. try running `pnpm run db:generate` command shown on the screen (See image 1)
3. See error - ` ERR_PNPM_NO_SCRIPT  Missing script: db:generate` (See image 2)

**Expected behavior**

The generate command should exist

**Screenshots**

![image](https://github.com/nicoalbanese/kirimase/assets/38887390/3ec603ea-297d-4e96-a9c1-0647ba436807)

![image](https://github.com/nicoalbanese/kirimase/assets/38887390/7c13a99c-d4b5-492c-a054-c5e0c9e99039)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 38

**Comment by nicoalbanese** [comment]
Thanks! For now, I've just removed the generate command if t3 is detected. Cheers!
