### ISSUE TITLE
Double env validation files when using T3

### ISSUE THREAD

**Issue by thecmdrunner** [nicoalbanese/kirimase#121]
**Config File**
```json
{
  "hasSrc": true,
  "packages": [
    "drizzle",
    "trpc",
    "next-auth",
    "shadcn-ui",
    "stripe"
  ],
  "preferredPackageManager": "pnpm",
  "t3": true,
  "alias": "@",
  "rootPath": "src/",
  "orm": "drizzle",
  "auth": "next-auth",
  "provider": "planetscale",
  "driver": "mysql",
  "componentLib": "shadcn-ui"
}
```

**Describe the bug**
T3 now uses `env.js` instead of `env.mjs` file to store env validations, but Kirimase CLI creates an `env.mjs` anyway, instead of adding the required variables in the existing `env.js`.

**To Reproduce**
1. Init with T3 - next-auth and Drizzle
2. Init kirimase with Stripe
3. See multiple env files - `env.js` (made by T3) and `env.mjs` (made by Kirimase)

**Expected behavior**
Kirimase should add the required variables in the existing `env.js` file if it exists

**Screenshots**
![image](https://github.com/nicoalbanese/kirimase/assets/38887390/98f86ad5-bdb0-43b7-ab96-44e94415d8e6)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 38

**Comment by nicoalbanese** [comment]
Thanks for flagging! Do you have any documentation on the new `.js` format as opposed to `.mjs` as the documentation I've found still uses that format.
