### ISSUE TITLE
Configuring Nrisma  ERROR  Failed to run Prisma generate: Command failed with exit code 1: pnpm prisma generate 

### ISSUE THREAD

**Issue by sharull9** [nicoalbanese/kirimase#133]
**Config File**
```
{
  "hasSrc": true,
  "packages": [
    "shadcn-ui",
    "prisma",
    "next-auth",
    "trpc",
    "resend",
    "stripe"
  ],
  "preferredPackageManager": "pnpm",
  "t3": false,
  "alias": "@",
  "rootPath": "src/",
  "componentLib": "shadcn-ui",
  "provider": "planetscale",
  "orm": "prisma",
  "driver": "mysql",
  "auth": "next-auth"
}
```
**Describe the bug**
When initiating kirimase init and choosing prisma for orm it show configuring Nrisma and It failed the command but complete the other parts

**To Reproduce**
kirimase init 
- shadcn/ui
- primsa - mysql - planetscale (y)
- auth.js (google, github)
- trpc, stripe, resend

**Expected behavior**
I dont know why it is crashing but my prisma schema should be generated

**Screenshots**
![prisma-exit](https://github.com/nicoalbanese/kirimase/assets/110934936/438e6354-1240-4f89-862a-568fecda8061)

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome
 - 121.0.6167.161

**Comment by nicoalbanese** [comment]
Thanks for flagging - this was happening because prisma generate is trying to run before prisma has been installed. This has been fixed and will be pushed in the next update coming later today.
