### ISSUE TITLE
Module '"@/lib/db/index"' has no exported member 'pool'.

### ISSUE THREAD

**Issue by sharull9** [nicoalbanese/kirimase#135]
**Config File**
```
{
  "hasSrc": true,
  "packages": [
    "shadcn-ui",
    "drizzle",
    "lucia",
    "trpc",
    "resend",
    "stripe"
  ],
  "preferredPackageManager": "pnpm",
  "t3": false,
  "alias": "@",
  "rootPath": "src/",
  "componentLib": "shadcn-ui",
  "driver": "pg",
  "provider": "supabase",
  "orm": "drizzle",
  "auth": "lucia"
}
```

**Describe the bug**
Module '"@/lib/db/index"' has no exported member 'pool'.

**To Reproduce**
Normal installed with packages in config file

**Expected behavior**
There should have been a pool export /lib/db/index

**Screenshots**
![image](https://github.com/nicoalbanese/kirimase/assets/110934936/9bce1c08-8408-4767-8b04-e228732005f3)

**Desktop (please complete the following information):**
 - OS: Windows
 - chrome

**Comment by iarata** [comment]
Not sure why there is no `pool` export in `@/lib/db/index` when using Lucia and drizzle but this is how I fixed it:

1. Install `pg` dependency (also `@types/pg` as dev dependency)
2. In `@/lib/db/index` import the Pool: `import { Pool } from 'pg'`
3. Add the following at the end of the `@/lib/db/index` file: 
```typescript
export const pool = new Pool({
    // connectionString: env.DATABASE_URL
    connectionString: connectionString,
})
```

**Comment by nicoalbanese** [comment]
With Lucia v3 this is now fixed!
