### ISSUE TITLE
Support Lucia v3

### ISSUE THREAD

**Issue by corentinclichy** [nicoalbanese/kirimase#136]
Hello,

There are a lot of change in Lucia v3, the Kirimase init is broken using old Lucia method. 

Would be awesome to add the support for the v3

**Comment by nicoalbanese** [comment]
Hey! Thanks - this is something on the near-term roadmap. The lucia configuration works so long as you don't upgrade the package. Hoping to have some updates on this in the coming weeks.

**Comment by corentinclichy** [comment]
Thanks a lot! Indeed i downgraded the version for now. 

Really like your product thanks for the good work !

**Comment by afogel** [comment]
ready to close :)
