### ISSUE TITLE
[Feature Request] Generate .gitignore with .env file added

### ISSUE THREAD

**Issue by nikolaischunk** [nicoalbanese/kirimase#147]
**Is your feature request related to a problem? Please describe.**
Since a `.env` file is generated I would suggest adding all `.env*` files to the `.gitignore` plus add `node_modules` also.

**Comment by nikolaischunk** [comment]
nevermind, it gets added with the create next app, and modifying the gitignore is not in scope for this project

**Comment by trevorpfiz** [comment]
> nevermind, it gets added with the create next app, and modifying the gitignore is not in scope for this project

just ran into this. having to explicitly set `.env` to be private is crazy to me.
