### ISSUE TITLE
[Feature Request] File Storage support

### ISSUE THREAD

**Issue by knajjars** [nicoalbanese/kirimase#154]
**Is your feature request related to a problem? Please describe.**
One of the main features when looking for a fullstack solution is the file storage, there are libraries that easily integrate with Nextjs like uploadthing, maybe this would be something interesting to add!

**Describe the solution you'd like**
Users can select a file storage from certain options: vercel blob, uploadthing, s3 API or a generic solution which accepts different adapters that are s3-compatible.

**Comment by Marknjo** [comment]
@knajjars  This is in support of your feature request. I also believe it would be great to have this feature integration. I'll probably come back later with code suggestion especially for media management UI in the dashboard.
