### ISSUE TITLE
Generating Prisma missing in build that is read by Vercel

### ISSUE THREAD

**Issue by navidre** [nicoalbanese/kirimase#155]
**Config File**
{
  "hasSrc": false,
  "packages": [
    "shadcn-ui",
    "prisma",
    "clerk",
    "resend",
    "stripe"
  ],
  "preferredPackageManager": "pnpm",
  "t3": false,
  "alias": "@",
  "analytics": true,
  "rootPath": "",
  "componentLib": "shadcn-ui",
  "orm": "prisma",
  "driver": "pg",
  "auth": "clerk"
}

**Describe the bug**
The package.json settings for dev and build should consider generating prisma first

Instead of 
"scripts": {
    "dev": "next dev",
    "build": "next build",
}

It should be:
"scripts": {
    "dev": "prisma generate && next dev",
    "build": "prisma generate && next build",
}

Otherwise, the build part causes error in deployment, e.g. in Vercel

**Comment by nicoalbanese** [comment]
Good shout - sorted!
