### ISSUE TITLE
use src/app/globals.css if "src" folder was already indicated

### ISSUE THREAD

**Issue by BeauSLM** [nicoalbanese/kirimase#17]
The cli asks if I'm using an src folder. iIf I answer yes, it will still default to app/globals.css later when it asks where my globals.css is.

It seems sensible that the cli assumes src/app/globals.css when its told that src/ is being used.

Repro:
- create-next-app with default settings (or however)
- `kirimase init`
- answer yes when asked if using `src/`
- when asked where globals.css is, it will still assume `app/globals.css` without the parent dir `src/`

**Comment by Sa-ar** [comment]
ShadCN UI does not support args in its init installation
https://ui.shadcn.com/docs/cli
So, for now, it's either creating some kind of a manual installation of ShadCN UI or solving it in the original ShadCN UI repo and allowing it there so it will be possible to send arguments to it through the CLI such as the directory of the location of the globals.css file.

**Comment by nicoalbanese** [comment]
This is now resolved! Kirimase no longer invokes the default Shadcn UI CLI, opting to install all elements manually.
