### ISSUE TITLE
db:push script missing from drizzle and postgres configuration

### ISSUE THREAD

**Issue by JulioBarros** [nicoalbanese/kirimase#185]
**Config File**
{
  "hasSrc": true,
  "packages": [
    "shadcn-ui",
    "drizzle",
    "lucia"
  ],
  "preferredPackageManager": "pnpm",
  "t3": false,
  "alias": "@",
  "analytics": true,
  "rootPath": "src/",
  "componentLib": "shadcn-ui",
  "driver": "pg",
  "provider": "postgresjs",
  "orm": "drizzle",
  "auth": "lucia"
}

**Describe the bug**
I used `pnpm dlx kirimase@latest init` to create a new project. It all seemed to work fine but the `"db:push": "drizzle-kit push:pg",` was missing from package.json.

I believe it should be there. If not, sorry about the confusion.

**To Reproduce**
Create a new project with the options above.

**Expected behavior**
It should have the db:push command

**Desktop (please complete the following information):**
MacOS 14.4.1

**Comment by nicoalbanese** [comment]
fixed with #196
