### ISSUE TITLE
Would need to update Drizzle DB generate command

### ISSUE THREAD

**Issue by shafinshaikh** [nicoalbanese/kirimase#197]
**Config File**
{
  "hasSrc": false,
  "packages": [
    "shadcn-ui",
    "drizzle",
    "lucia"
  ],
  "preferredPackageManager": "npm",
  "t3": false,
  "alias": "@",
  "analytics": true,
  "rootPath": "",
  "componentLib": "shadcn-ui",
  "driver": "sqlite",
  "provider": "better-sqlite3",
  "orm": "drizzle",
  "auth": "lucia"
}

**Description of the bug**
![image](https://github.com/nicoalbanese/kirimase/assets/26216093/2743b33b-9056-408a-8148-6b0634461199)
While running "npm run db:generate" I get the error " This command is deprecated, please use updated 'generate' command (see https://orm.drizzle.team/kit-docs/upgrade-21#how-to-migrate-to-0210)"
Here are logs:
> tokenwale@0.1.0 db:generate
> drizzle-kit generate:sqlite

**To Reproduce**
1. Go via kirimase config route 
2. Try generating first instance of db
3. See error

**Expected behavior**
Drizzle db should be generated at this particular step

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Chrome 125 on Windows 11

**Comment by nicoalbanese** [comment]
Resolved with #194
