### ISSUE TITLE
 The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

### ISSUE THREAD

**Issue by Mdkawsarislam2002** [nicoalbanese/kirimase#20]
When I tried to use it, It showed   this error 

![image](https://github.com/nicoalbanese/kirimase/assets/87494463/67f6e09f-3bdb-4bdc-8c5e-875c0fe5bb0f)

**Comment by nicoalbanese** [comment]
Thanks - I hadn't expected next-auth to be installed without drizzle, and so it was trying to pull in drizzle config here. This has been resolved and will be updated once I publish the next version on NPM. Cheers.
