### ISSUE TITLE
kirimase init logs a dependecy conflict

### ISSUE THREAD

**Issue by deelanMaha** [nicoalbanese/kirimase#200]
**Describe the bug**
After creating a new Next app with `npx create-next-app@latest`, I go into the new projet and launch `kirimase init` with the same options as used in the Youtube tutorial (I believe it's called "From zero to prod in seconds" or something along those lines), so Shadcn UI, Drizzele, Vercel Postgres, Lucia

**Screenshots**
<img width="710" alt="image" src="https://github.com/nicoalbanese/kirimase/assets/154598720/c4831041-4a93-47e4-b446-03d93b048992">

**Desktop (please complete the following information):**
 - OS: Mac 
 - Version : latest version (up to today's date of course)

**Comment by rhuddlestone** [comment]
This happens to me when I use npm, try using pnpm to create next app.  This works for me.

**Comment by nicoalbanese** [comment]
Hey! Yes this is a known issue with npm / drizzle 
Solution is as mentioned by @rhuddlestone 
#198

**Comment by deelanMaha** [comment]
Thank you so much guys !
