### ISSUE TITLE
not from the package but need help

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [nicoalbanese/kirimase#22]
I'm getting this error when trying to use this
```ts
// RSC page 
const checkOnboard = await api.user.checkOnboarding.query();
```

<img width="1153" alt="Screenshot 2023-09-09 at 17 33 24" src="https://github.com/nicoalbanese/kirimase/assets/74371045/7f395277-4283-4da4-af6d-150e5e0f57f8">

not sure if it's related to TRPC or planetscale itself 😢

I'm using the default implementation from kirimase for trpc on rsc

**Comment by nicoalbanese** [comment]
Hey! Yes this seems to be related to ongoing cache issues that the nextjs team are hopefully resolving in the near future. Also discussed here #14. Will close for now as nothing I can do on my end but reopen once there are updates from the next team.
