### ISSUE TITLE
When selecting mysql2, a sqlite connector is created instead.

### ISSUE THREAD

**Issue by ramoneres** [nicoalbanese/kirimase#24]
As the title says. Kirimase creates the wrong connector for mysql2.

![image](https://github.com/nicoalbanese/kirimase/assets/79410235/c3959d9b-5c38-4f70-b131-0d4c57dabffe)

![image](https://github.com/nicoalbanese/kirimase/assets/79410235/ea20a497-cd1d-44f3-8ec7-06dcde10448b)

I replaced it with this and it works fine. But i'm not sure if it's the best way to do it. Maybe it should be a pool connection.

![image](https://github.com/nicoalbanese/kirimase/assets/79410235/255425f7-895d-452a-a22f-e0cce7d2cddd)

A separate issue: Migrating does not work with maria db. I know they are different, but yeah. Just to let you know.

![image](https://github.com/nicoalbanese/kirimase/assets/79410235/21107ed1-a4aa-4a9f-af9f-9761b5d172a1)

**Comment by nicoalbanese** [comment]
Hey! Thanks for flagging. This was as a result of a silly mistake on my end. This should be resolved now with v0.0.11
