### ISSUE TITLE
BUG: SQlite+SignIn ! 

### ISSUE THREAD

**Issue by mehdi-cit** [nicoalbanese/kirimase#31]
Hello and thank you for this promissing project!
Followed the Demo but picked **Sqlite** and no third party auth provider (assuming it will simply use the sqlite for authentication).
Importing the provided **SignIn** and using it on the Home page works well (as shown in the DEMO).
However, clicking on the **SignIn** button leads to "the" error page: **http://localhost:3000/api/auth/error** 
No info in the console log. Inspecting the Network tab shows a 200 OK request to http://localhost:3000/**api/auth/providers** followed immediately by redirection to the error page: http://localhost:3000/**api/auth/error**
![image](https://github.com/nicoalbanese/kirimase/assets/2162107/916882ae-83da-48bb-b961-95d64ea5787d)

**Comment by nicoalbanese** [comment]
Hey Mehdi - thanks for the issue. Just to clarify, did you install next-auth but didn't select any auth-providers (github, discord etc.)? If that is the case, you would have to pick a provider because this error would be as a result of not having any providers to sign you in with.

**Comment by mehdi-cit** [comment]
I did as per the demo (almost since the options were not proposed in the same order). I did not pick any of the proposed auth providers (Github, Google, Apple, discord ...). I assumed the "normal" username/email + password would be a default!
Are you saying one MUST pick a third party provider?

**Comment by nicoalbanese** [comment]
That is correct, yes. For email sign in, you have to configure either credentials or email-magic-link signin (https://authjs.dev/getting-started/email-tutorial?frameworks=next).
