### ISSUE TITLE
Fix: Clerk redirect

### ISSUE THREAD

**Issue by njdowdy** [nicoalbanese/kirimase#40]
Clerk was giving me a 404 on redirect to '/' (and other routes) after trying to use OAuth. 

The fix was to change the folder structure for Clerk sign-in and sign-up to include a catch-all segment. 

The following replacements needed to be made:
`src/app/sign-in/page.tsx` -> `src/app/sign-in/[[...sign-in]]/page.tsx`
`src/app/sign-up/page.tsx` -> `src/app/sign-up/[[...sign-up]]/page.tsx`

See the Clerk quick start for more info: [https://clerk.com/docs/quickstarts/nextjs#build-your-sign-in-page](https://clerk.com/docs/quickstarts/nextjs#build-your-sign-in-page)

**Comment by nicoalbanese** [comment]
Thanks - have updated
