### ISSUE TITLE
TypeError: Property 'readonly' is missing

### ISSUE THREAD

**Issue by njdowdy** [nicoalbanese/kirimase#42]
The example db schema `src/lib/db/schema/computers.ts` produces a TypeScript error when trying to infer the type from the generated schema as in `z.infer<typeof selectComputerSchema>`.

Not a major issue, but causes build failure which is unfortunate. Any help is much appreciated!

The error:
```
Type 'ZodObject<{ id: ZodNumber; brand: ZodString; cores: ZodNumber; }, UnknownKeysParam, ZodTypeAny, { id: number; brand: string; cores: number; }, { ...; }>' does not satisfy the constraint 'ZodType<any, any, any>'.

Property 'readonly' is missing in type 'ZodObject<{ id: ZodNumber; brand: ZodString; cores: ZodNumber; }, UnknownKeysParam, ZodTypeAny, { id: number; brand: string; cores: number; }, { ...; }>' but required in type 'ZodType<any, any, any>'.ts(2344)

types.d.ts(91, 5): 'readonly' is declared here.
```

I guess the readonly aspect is an issue with Zod. I found something kinda similar [here](https://github.com/colinhacks/zod/issues/831#issuecomment-1054471573) that adds `as const`, but trying that yields:

`A 'const' assertions can only be applied to references to enum members, or string, number, boolean, array, or object literals.ts(1355)`

I'll keep investigating, but I'm just a TypeScript novice. 

My `kirimase.config.json`:
```
{
  "hasSrc": true,
  "packages": [
    "drizzle",
    "clerk",
    "trpc"
  ],
  "preferredPackageManager": "bun",
  "rootPath": "src/",
  "driver": "pg",
  "provider": "supabase",
  "orm": "drizzle",
  "auth": "clerk"
}
```

**Comment by njdowdy** [comment]
I altered the contents of `src/lib/db/schema/computers.ts` to the following, which resolved the issue.... however I do not know at what cost 😅 I'm really not sure what the implications of dropping the `z.infer` are here. Someone with better knowledge should really review. But it seems that code completion and the build step are happy.

```
import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
//import { z } from 'zod'; //! import no longer used
import { pgTable, serial, text, integer } from "drizzle-orm/pg-core";


export const computers = pgTable("computers", {
  id: serial("id").primaryKey(),
  brand: text("brand").notNull(),
  cores: integer("cores").notNull(),
});
// Schema for CRUD - used to validate API requests
export const insertComputerSchema = createInsertSchema(computers);
export const selectComputerSchema = createSelectSchema(computers);
export const computerIdSchema = selectComputerSchema.pick({ id: true });
export const updateComputerSchema = selectComputerSchema;

//! the relevant changes:
// export type Computer = z.infer<typeof selectComputerSchema>;
export type Computer = typeof computers.$inferSelect;
// export type NewComputer = z.infer<typeof insertComputerSchema>;
export type NewComputer = typeof computers.$inferInsert;
// export type ComputerId = z.infer<typeof computerIdSchema>["id"];
export type ComputerId = typeof computerIdSchema._type["id"]
```

**Comment by Apestein** [comment]
+1

**Comment by marvkr** [comment]
Had this issue when using Bun, it's a version mismatch between Drizzle-Zod & Zod. Would recommend not using Bun at the moment, switched back to pnpm & everything worked

**Comment by njdowdy** [comment]
Tried a new project today using:

- bun: 1.0.4 (was 1.0.1)
- drizzle-zod: "^0.5.1" (was "^0.5.1")
- zod: "^3.22.4" (was "^3.22.2")

And the issue appears resolved. So, @marvkr appears to be correct and the issue was resolved in those other repos. 

Thanks!
