### ISSUE TITLE
Add CredentialProvider option for Auth.js

### ISSUE THREAD

**Issue by avireddymatta** [nicoalbanese/kirimase#43]
Hi, 

I love this project, it saves time through the setup and giving a proper folder structure.

In this setup when i choose Auth.js i see Discord, Google, GitHub, but no Credentials Provider option.

Auth.js official website states that they are discouraging "Credentials Provider" as part of there providers setup but in real world most people still use UserName/Email and Password login. 

At the end of the day developer have to do what CLIENT wants, but not the other way around. Can you please provide Credentials option in Auth.js, 
since setting up Credentials option is not as easy as setting up google.

**Comment by nicoalbanese** [comment]
Hey! Given this is something the authjs team has recommended against and it's not the easiest to implement, I've decided to go with adding Lucia as an authentication provider as an alternative. Hope it helps!
