### ISSUE TITLE
Google Auth Erroring out 

### ISSUE THREAD

**Issue by ParkerRex** [nicoalbanese/kirimase#47]
Started with a fresh project.

I've used Nextauth + Google provider a handful of times before.

Added my Google client id and google client secret to the .env but still having issues. 

Dying to get this working because I can't _imagine_ how fast you can move with that generate function. 

<img width="976" alt="SCR-20230918-suop" src="https://github.com/nicoalbanese/kirimase/assets/20405449/56bad77b-9525-479e-b15d-c5c6676d209f">

<img width="161" alt="image" src="https://github.com/nicoalbanese/kirimase/assets/20405449/73062982-d1d7-4eac-ad03-29d144fab995">

**Comment by ParkerRex** [comment]
yeap I had the wrong client id from another project. 

JK. 

Pumped about this project 👍

**Comment by nicoalbanese** [comment]
Ha no stress - happy to hear!
