### ISSUE TITLE
After Intializing a project using Kirimase i get this error when i execute npx prisma generate

### ISSUE THREAD

**Issue by abdou6666** [nicoalbanese/kirimase#55]
I configured the project to use NextAuth ,Planetscale , MySQL , Shadcn ui ,  trpc , tailwindcss , typescript , resend

Repo : https://github.com/abdou6666/coachini-app
_____________________________
Error when i execute npx prisma generate :

Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: Get config: Schema Parsing P1012

error: Error validating: This line is not a valid definition within a generator.
  -->  schema.prisma:10
   | 
 9 |   provider              = "zod-prisma"
10 |   output                = "./zod" // (default) the directory where generated zod schemas will be saved
11 |   relationModel         = true // (default) Create and export both plain and related models.
   | 
error: Error validating: This line is not a valid definition within a generator.
  -->  schema.prisma:11
   | 
10 |   output                = "./zod" // (default) the directory where generated zod schemas will be saved
11 |   relationModel         = true // (default) Create and export both plain and related models.
12 |   modelCase             = "camelCase" // Output models using camel case (ex. userModel, postModel)
   | 
error: Error validating: This line is not a valid definition within a generator.
  -->  schema.prisma:12
   | 
11 |   relationModel         = true // (default) Create and export both plain and related models.
12 |   modelCase             = "camelCase" // Output models using camel case (ex. userModel, postModel)
13 |   modelSuffix           = "Schema" // (default) Suffix to apply to your prisma models when naming Zod schemas
   | 
error: Error validating: This line is not a valid definition within a generator.
  -->  schema.prisma:13
   | 
12 |   modelCase             = "camelCase" // Output models using camel case (ex. userModel, postModel)
13 |   modelSuffix           = "Schema" // (default) Suffix to apply to your prisma models when naming Zod schemas
14 |   useDecimalJs          = true // represent the prisma Decimal type using Decimal.js (as Prisma does)
   | 
error: Error validating: This line is not a valid definition within a generator.
  -->  schema.prisma:14
   | 
13 |   modelSuffix           = "Schema" // (default) Suffix to apply to your prisma models when naming Zod schemas
14 |   useDecimalJs          = true // represent the prisma Decimal type using Decimal.js (as Prisma does)
15 |   prismaJsonNullability = true // (default) uses prisma's scheme for JSON field nullability
   | 
error: Error validating: This line is not a valid definition within a generator.
  -->  schema.prisma:15
   | 
14 |   useDecimalJs          = true // represent the prisma Decimal type using Decimal.js (as Prisma does)
15 |   prismaJsonNullability = true // (default) uses prisma's scheme for JSON field nullability
16 | }
   | 

Validation Error Count: 6

Prisma CLI Version : 3.15.2

**Comment by abdou6666** [comment]
it turns out zod-prisma installation failed during project creation (i think its cause prisma clashing versions) i had to install it manually with --force

**Comment by abdou6666** [comment]
I recommend swaping to zod-prisma-types instead it's still being maintained unlike zod-prisma and it works with prisma v5 but it needs zod 3.21.1 or less (known issue) 
https://github.com/chrishoermann/zod-prisma-types

**Comment by Goldennboyy** [comment]
I guess i'll have to wait for the next patch before using it

**Comment by Ainsdev** [comment]
Change it to:

```
generator zod {
  provider = "zod-prisma"
}
```

That works for me

**Comment by dinhkhanh** [comment]
This was fixed by #69 
Update to latest version should make it works.
