### ISSUE TITLE
not issue but feature request: Add lucia oAuth

### ISSUE THREAD

**Issue by statusunknown418** [nicoalbanese/kirimase#57]
would be really nice to have this too, apart from the usual next-auth (having trouble with edge and slow performance recently) and clerk (can become pricey fast)

**Comment by AlvaroAquijeDiaz** [comment]
https://supertokens.com/ - ref supertokens
https://kinde.com/docs/developer-tools/nextjs-sdk/ - ref kinde nextjs 13
