### ISSUE TITLE
Feature Request: Stripe Subscription and Payment Integration

### ISSUE THREAD

**Issue by sergioUjo** [nicoalbanese/kirimase#60]
I would like to propose the addition of a feature that seamlessly integrates Stripe subscription and payment functionality into the command-line tool.

**Comment by nicoalbanese** [comment]
Almost done 😊

**Comment by sergioUjo** [comment]
> Almost done 😊

Really, awesome can't wait that would be my entire stack :)

**Comment by nicoalbanese** [comment]
Done!
