### ISSUE TITLE
Non-interactive mode for CLI

### ISSUE THREAD

**Issue by nelsonfrz** [nicoalbanese/kirimase#7]
As a user I would like to pass command line arguments to set up a new project non-interactively. 

That allows users to initialize kirimase using command line arguments e.g. these:
--src-dir/--no-src-dir
--use-npm/--use-pnpm/--use-yarn 
--packages <packages>
--use-postgres <postgres-db-provider>/--use-mysql <mysql-db-provider>/--use-sqllite <sqllite-db-provider>
--include-example-model
...

That allows users to generate models using command line arguments e.g. these:
--resources <resources>
--table-name <table-name>
--fields <fields>
--setup-index
--belongs-to-user
....

**Comment by elie222** [comment]
@nicoalbanese are you open to accepting a PR to add this functionality?

**Comment by nicoalbanese** [comment]
Absolutely!
