### ISSUE TITLE
More Typescript errors

### ISSUE THREAD

**Issue by sangrepura** [nicoalbanese/kirimase#70]
## Summary
name: Typescript Error
about:  Module '"@/lib/auth/utils"' declares 'AuthSession' locally, but it is not exported.
labels: bug

## Bug Description
Type errors in generated code.  

```
tsc --project ./tsconfig.json

src/app/account/PlanSettings.tsx:9:10 - error TS2459: Module '"@/lib/auth/utils"' declares 'AuthSession' locally, but it is not exported.

9 import { AuthSession } from "@/lib/auth/utils";
           ~~~~~~~~~~~

  src/lib/auth/utils.ts:4:6
    4 type AuthSession = {
           ~~~~~~~~~~~
    'AuthSession' is declared here.

src/app/account/UserSettings.tsx:4:10 - error TS2459: Module '"@/lib/auth/utils"' declares 'AuthSession' locally, but it is not exported.

4 import { AuthSession } from "@/lib/auth/utils";
           ~~~~~~~~~~~

  src/lib/auth/utils.ts:4:6
    4 type AuthSession = {
           ~~~~~~~~~~~
    'AuthSession' is declared here.


Found 2 errors in 2 files.

Errors  Files
     1  src/app/account/PlanSettings.tsx:9
     1  src/app/account/UserSettings.tsx:4

```

Looks like we just forgot to export the type in `src/lib/auth/utils.ts` this time.

Just my $.02, but I think adding an integration test that runs `tsc --project ./tsconfig.json` to catch these errors after generating a project directory (before tagging a public release) would really improve the developer experience.

**Comment by nicoalbanese** [comment]
Hey @sangrepura - thanks for this! Yes silly mistake from my end. Will push changes as part of next update. Would absolutely love to have tests as I'm doing them manually and it sucks. Any suggestions? I've never built or run tests before, and wouldn't know where to start with a CLI like this.

**Comment by mcapodici** [comment]
I would make a test at the shell level that invokes the tool, installs everything then builds and lints the resulting code. If the exit code is not 0 it fails. This will work well with CI.

**Comment by dinhkhanh** [comment]
Any updates? @nicoalbanese 
The latest release (3 days ago) doesn't include this fix?

**Comment by nicoalbanese** [comment]
@dinhkhanh hey - this was fixed but I put out another update yesterday that introduced an error here if you are using next auth. I’ll take a look today.

**Comment by nicoalbanese** [comment]
Should be sorted with 0.0.32!
