### ISSUE TITLE
shadcn not in place even after choosing it for UI

### ISSUE THREAD

**Issue by smadikanti** [nicoalbanese/kirimase#72]
<img width="884" alt="Screenshot 2023-10-25 at 1 19 03 AM" src="https://github.com/nicoalbanese/kirimase/assets/31075637/4defffee-4d71-47fd-b36e-47ead049ab7f">

**Comment by smadikanti** [comment]
App looks like this with NO shadcn ui components.
<img width="777" alt="Screenshot 2023-10-25 at 1 20 14 AM" src="https://github.com/nicoalbanese/kirimase/assets/31075637/5d0d3277-7330-4900-9ba9-aee31ce20647">

**Comment by nicoalbanese** [comment]
@smadikanti Hey! My guess is that it's something to do with the globals.css file not being picked up properly given all the fonts are off too. Can you send a screenshot of the entire project directory?
