### ISSUE TITLE
Regeneration of the same model name causes issues

### ISSUE THREAD

**Issue by nelsonfrz** [nicoalbanese/kirimase#8]
When I generate a model with the same name twice then the model gets imported twice in _app root router.

![image](https://github.com/nicoalbanese/kirimase/assets/117679845/fe450900-ba31-4b13-85ea-354ca81cb96c)

Either disallow generating models with the same name twice or allow overwriting (notify the user) with only one import in _app root router.

**Comment by nicoalbanese** [comment]
Hey Nelson - thanks for flagging this! I've left the default behaviour as overwriting the current model with that same name, but have added logic to stop it adding another entry to the root router. Cheers!
