### ISSUE TITLE
npx kirimase init fails for new next app using javascript "no such file or directory, open 'tsconfig.json'"

### ISSUE THREAD

**Issue by dcourv** [nicoalbanese/kirimase#80]
After running the following:
`npx create-next-app@latest next-app`
**`> typescript: no`**
`> eslint: yes`
`> tailwind: yes`
`> src dir: yes`
`> app router: yes`
`> customize import alias: no`

(in next-app directory)
`npx kirimase@latest init`
`> src dir: yes`
`> preferred package manager: npm`

I get the following error:
``` FATAL  No TSConfig found...                                       10:12:50 PM

node:fs:453
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open 'tsconfig.json'
    at readFileSync (node:fs:453:20)
    at Command.initProject (file:///Users/dcourv/.npm/_npx/6b95167c46caeb29/node_modules/kirimase/dist/commands/init/index.js:50:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'tsconfig.json'
}

Node.js v21.1.0```

**Comment by nicoalbanese** [comment]
ahh this is a good point somehow hasn't come up until now. Living in my typescript bubble I completely forgot to add a check for that and add some copy stating that Kirimase is only compatible with typescript projects. Sorry about that but thanks for flagging and I'll have a fix up shortly to avoid happening again.
