### ISSUE TITLE
Init fails on new app with trpc

### ISSUE THREAD

**Issue by diogoribeirodev** [nicoalbanese/kirimase#83]
Hi, i created a new app using t3. When i run kirimase init, i get this error, initially i thought it was bc i was using "@" as the import alias rather the t3 default one ("~"), but i tested with both and i get the error with both, also it appears the cli is not recognizing the app being   created using t3 (check second pic), i tried setting it to true but didnt work either.
![image](https://github.com/nicoalbanese/kirimase/assets/81532541/d046d2cb-572d-42da-8639-ad47e5ff3fff)
![image](https://github.com/nicoalbanese/kirimase/assets/81532541/04d89239-f0f8-42c4-b277-633402ceddbd)

**Comment by nicoalbanese** [comment]
Thanks for flagging - this was happening as the t3 team has added comments to the TSConfig in the latest update which was leading to JSON parse failing. I've added a package to remove comments that has resolved the issue. Should be good to go with 0.0.33
