### ISSUE TITLE
[Feature Request] Server Actions

### ISSUE THREAD

**Issue by leerob** [nicoalbanese/kirimase#86]
You can achieve E2E type safety in the App Router with the combination of Server Components and Server Actions. With this combination, you should rarely need to use Route Handlers for custom API routes, except in cases like scaffolding out authentication endpoints.

**Comment by nicoalbanese** [comment]
@leerob huge fanboy moment! Your FastFeedback course was how I learned Nextjs a few years back 😊

And yes definitely keen to add Server Actions as an option for the generate command. Will try and get something pulled together this week.

**Comment by nicoalbanese** [comment]
Server Actions now available in 0.0.38! Really enjoyed building this out. It took longer than expected as it required rethinking of the previous generate architecture (now much improved). All in all, really impressed with how much we can do with just react/nextjs without reaching for outside libraries now!
