### ISSUE TITLE
Stale data using experimental_nextCacheLink 

### ISSUE THREAD

**Issue by Ipicon** [nicoalbanese/kirimase#89]
After a whole day of debugging why am I getting stale data even though I revalidate everything, I saw this discussion:
[https://discord-questions.trpc.io/m/1150707553068650579](https://discord-questions.trpc.io/m/1150707553068650579)

the problem with this, is that the `api` variable doesn't sit under the context (because it's on the server), and when calling revalidate it doesn't effect all server rendered components.

now managing the cache on the `api` var is quite a hustle, maybe we should approach this like T3 does?
create a custom RSC link that lets us invoke procedures without using http at all.

**Comment by nicoalbanese** [comment]
Hey! Yes I’ve been running into issues too with context here. Planning on
updating implementation to t3s’ later this week. Hopefully will resolve it
🤞

**Comment by Ipicon** [comment]
@nicoalbanese 
thanks for the fast reply.
I don't mind helping with a PR if you want

**Comment by nicoalbanese** [comment]
No stress - I had actually already started working on it a few days ago so figured fastest to just finish it off. Thanks!

**Comment by Ipicon** [comment]
@nicoalbanese 
another nice thing we can do is injecting the db prop inside the context, which can fix help with reconnection issues in some environments

**Comment by nicoalbanese** [comment]
@Ipicon check this out: https://github.com/nicoalbanese/kirimase/blob/c80277c24c072ba8f18cdfa6766a6e4d95d55002/src/commands/add/misc/trpc/generators.ts#L321

This was the same approach t3 had, putting it directly into the context. Is that what you mean?

**Comment by Ipicon** [comment]
@nicoalbanese exactly!
I already went over this commit and saw you did it.😁
