### ISSUE TITLE
Add support for Prisma ORM

### ISSUE THREAD

**Issue by Armadillidiid** [nicoalbanese/kirimase#9]
Hey there! I'm really excited about the CLI package, but I've been thinking, it would be awesome if we could add support for Prisma. Right now, it's all about Drizzle ORM, but having Prisma as an option would give users more freedom to choose what suits them best.

**Comment by Goldennboyy** [comment]
facts, I  was about to add this comment

**Comment by nicoalbanese** [comment]
Hi guys - I've just released 0.0.11 which supports Prisma now! Give it a go and let me know if you have any issues.
