### ISSUE TITLE
Missing script: `pnpm run prisma migrate dev` 

### ISSUE THREAD

**Issue by elie222** [nicoalbanese/kirimase#94]
This error shows up when adding a new model:

```
 ERR_PNPM_NO_SCRIPT  Missing script: prisma

Command "prisma" not found.
```

To fix manually I ran prisma myself.

**Comment by nicoalbanese** [comment]
have you tried running the command without `run`? From the docs[1] it's suggested to run `pnpm dlx prisma *command*` although `pnpm prisma *command*` works too

1. https://www.prisma.io/docs/reference/api-reference/command-reference

**Comment by elie222** [comment]
Hey, I just I was on version 0.17 so this may be why I was seeing issues. I'll close these soon as it's probably not an error on latest version.

**Comment by nicoalbanese** [comment]
No stress at all - happy you got it sorted!
